AzureMonitorMetrics:
  ImageRepository: mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images
  ImageTag: 6.8.0-ccp-shell-removal-branch-11-07-2023-ecf80996
  # The below 2 settings are not Azure Monitor Metrics adapter chart. They are substituted in a different manner.
  # Please update these with the latest ones from here so that you get the image that is currently deployed by the AKS RP -
  # Repository: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/addon-charts/azure-monitor-metrics-addon/templates/ama-metrics-daemonset.yaml&version=GBrashmi/prom-addon-arm64&line=136&lineEnd=136&lineStartColumn=56&lineEndColumn=85&lineStyle=plain&_a=contents
  # ImageTag: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/kube-control-plane/templates/_images.tpl&version=GBrashmi/prom-addon-arm64&line=530&lineEnd=530&lineStartColumn=28&lineEndColumn=53&lineStyle=plain&_a=contents
  ArcExtension: false
  # Do not change the below settings. They are reserved for Arc Autonomous
  isArcACluster: false
global:
  commonGlobals:
    CloudEnvironment: "azurepubliccloud"
    Region: "eastus"
    Customer:
      AzureResourceID: "/subscriptions/feb5b150-60fe-4441-be73-8c02a524f55a/resourceGroups/standalone-231027inzcx1/providers/Microsoft.ContainerService/managedClusters/standalone-231027inzcx1-cx-1"
      Namespace: 6548620671d73d0001715887
      SubscriptionId: feb5b150-60fe-4441-be73-8c02a524f55a #msi-adapter
      ResourceGroupName: standalone-231027inzcx1 #msi-adapter
      ManagedClusterName: standalone-231027inzcx1-cx-1 #msi-adapter
prometheus-node-exporter:
  service:
    port: 9110
    targetPort: 9110
