AzureMonitorMetrics:
  ImageRepository: ninaaksoperatore2e.azurecr.io/prometheus-collector
  ImageTag: 6.7.0-main-26-07-2023-67
  # The below 2 settings are not Azure Monitor Metrics adapter chart. They are substituted in a different manner.
  # Please update these with the latest ones from here so that you get the image that is currently deployed by the AKS RP -
  # Repository: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/addon-charts/azure-monitor-metrics-addon/templates/ama-metrics-daemonset.yaml&version=GBrashmi/prom-addon-arm64&line=136&lineEnd=136&lineStartColumn=56&lineEndColumn=85&lineStyle=plain&_a=contents
  # ImageTag: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/kube-control-plane/templates/_images.tpl&version=GBrashmi/prom-addon-arm64&line=530&lineEnd=530&lineStartColumn=28&lineEndColumn=53&lineStyle=plain&_a=contents
  ArcExtension: false
  # Do not change the below settings. They are reserved for Arc Autonomous
  isArcACluster: false
global:
  commonGlobals:
    CloudEnvironment: "azurepubliccloud"
    Region: "eastus"
    Customer:
      AzureResourceID: "/subscriptions/18153b17-4e27-4b58-863e-f8105b8892a2/resourceGroups/standalone-2309057cjg7s/providers/Microsoft.ContainerService/managedClusters/standalone-2309057cjg7s-cx-1"
      Namespace: 64ff84c4ce846f0001c5a5a2
      SubscriptionId: 18153b17-4e27-4b58-863e-f8105b8892a2 #msi-adapter
      ResourceGroupName: standalone-2309057cjg7s #msi-adapter
      ManagedClusterName: standalone-2309057cjg7s-cx-1 #msi-adapter
prometheus-node-exporter:
  service:
    port: 9110
    targetPort: 9110
